filter {
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:log_ts} %{DATA:service} %{LOGLEVEL:level} user=%{DATA:user} action=%{action} status=%{NUMBER:status:int} latency_ms=%{NUMBER:latency_ms:int}"
    }
  }
}
