input { stdin { } }

filter {
  dissect {
    mapping => {
      "message" => "%{log_ts} %{service} %{level} user=%{user} action=%{action} status=%{status}"
    }
  }
}

output { stdout { codec => rubydebug } }
