input { stdin { } }

filter {
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:log_ts} %{DATA:service} %{LOGLEVEL:level} user=%{DATA:user} action=%{DATA:action} status=%{NUMBER:status:int}"
    }
  }
}

output { stdout { codec => rubydebug } }
