input { stdin { } }

filter {
  if [service] == "payments" and [latency_ms] > 500 {
    mutate { add_tag => ["slow_payment"] }
  } else if [service] == "auth" and [status] != 200 {
    mutate { add_tag => ["auth_failure"] }
  } else if [env] == "prod" and [level] == "ERROR" {
    mutate { add_tag => ["prod_error"] }
  }
}

output { stdout { codec => rubydebug } }
