input { stdin { } }

filter {
  ruby {
    code => '
      payload = event.get("payload") || ""
      event.set("payload_sha", Digest::SHA256.hexdigest(payload))
      event.set("payload_length", payload.length)
    '
  }
}

output { stdout { codec => rubydebug } }
