input { stdin { } }

filter {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "user-profiles"
    query => "user_id:%{[user_id]}"
    fields => { "plan" => "user_plan" }
  }
}

output { stdout { codec => rubydebug } }
