input { stdin { } }
filter {
  dissect { mapping => { "message" => "%{log_ts} %{service} %{level} user=%{user} action=%{action} status=%{status} latency_ms=%{latency_ms}" } }
  mutate { convert => { "status" => "integer" "latency_ms" => "integer" } }
}
output { stdout { codec => rubydebug } }
