input { stdin { } }

filter {
  dissect {
    mapping => { "message" => "status=%{status}" }
  }

  mutate {
    convert => { "status" => "integer" }
  }

  if [status] == "200" {
    mutate { add_field => { "success" => true } }
  }
}

output { stdout { codec => rubydebug } }
