input {
  file {
    path => "${PWD}/samples/100k.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    mode => "read"
  }
}
filter {
  grok { match => { "message" => "%{GREEDYDATA:prefix} user=%{DATA:user} action=%{DATA:action} status=%{NUMBER:status:int} latency_ms=%{NUMBER:latency_ms:int}" } }
}
output { file { path => "${PWD}/results/grok-expensive.out" codec => "line" } }
