input {
  file {
    path => "${PWD}/samples/100k.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    mode => "read"
    file_completed_action => "log"
    file_completed_log_path => "/tmp/completed-dissect.log"
  }
}
filter {
  dissect { mapping => { "message" => "%{log_ts} %{service} %{level} user=%{user} action=%{action} status=%{status} latency_ms=%{latency_ms}" } }
  mutate { convert => { "status" => "integer" "latency_ms" => "integer" } }
}
output { file { path => "${PWD}/results/dissect.out" codec => "line" } }
